### PR TITLE
Add support for python 3.6

### PR DESCRIPTION
**Pull request by SeanMooney**
- This change increases the maxium
  version of python 3 to 3.6
- This change simplifes the tox.ini
  by deduplicating common sections.
- This change adds py36 to the default
  envlist.

### CODE REVIEW

**Comment by mriedem** [comment]
You should also update the setup.py:

https://github.com/mfcloud/python-zvm-sdk/blob/master/setup.py#L39

**Comment by mriedem** [comment]
LGTM now.

**Comment by jichenjc** [comment]
Thanks a lot for your help @SeanMooney , @mriedem we are using gerrit review to merge code, I copied the code to here https://review.gerrithub.io/c/mfcloud/python-zvm-sdk/+/419771

can you help to take a look and comment if you have 

by the way, what kind of error you encountered during your test @SeanMooney ? we just want to take this as reference, thanks

**Comment by SeanMooney** [comment]
this was the error.
http://paste.openstack.org/show/726237/
ill add it to the gerrit review too

**Comment by bjhuangr** [comment]
I believe the issue was resolved

**Pull request closed without merging**
